### ISSUE TITLE
Where can I download the pretrained model?

### ISSUE THREAD

**Issue by 3togo** [pgigioli/depth_net#1]
Where can I download the following data_sets?
/media/ai2-leia/data_disk/data_sets/robot_RGB-depth

**Comment by pgigioli** [comment]
Hi 3togo, unfortunately I cannot make the the dataset publicly available.  I collected the dataset by simultaneously capturing rgb and depth images using an ASUS Xtion Pro rgbd camera.  Otherwise, I may be able to upload the weights at a later time.  Hope that helps.
